name: finale
description: A fully-featured Last.fm client
publish_to: 'none'
version: 1.1.0+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^2.4.1
  crypto: ^2.1.5
  datetime_picker_formfield: ^1.0.0
  flutter:
    sdk: flutter
  flutter_acrcloud: ^0.0.2
  flutter_launcher_icons: ^0.8.1
  flutter_web_auth: ^0.2.4
  html: ^0.14.0+4
  http: ^0.12.2
  http_throttle: ^1.0.4
  in_app_review: ^1.0.4
  intl: ^0.16.1
  json_annotation: ^3.1.1
  modal_bottom_sheet: ^1.0.0+1
  package_info: ^0.4.3+2
  rxdart: ^0.25.0
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  social_media_buttons: ^0.1.2
  sqflite: ^1.3.2+1
  transparent_image: ^1.0.0
  url_launcher: ^5.7.10

dev_dependencies:
  build_runner: ^1.10.11
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true
