name: finale
description: A fully-featured Last.fm client
publish_to: 'none'
version: 1.5.1+21

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.1.0
  charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter
  collection: ^1.15.0
  crypto: ^3.0.1
  datetime_picker_formfield: ^2.0.0
  flutter:
    sdk: flutter
  flutter_acrcloud: ^0.1.3
  flutter_svg: ^0.22.0
  flutter_web_auth:
    git: https://github.com/czepiec/flutter_web_auth
  gallery_saver: ^2.3.1
  html: ^0.15.0
  http: ^0.13.4
  in_app_review: ^2.0.3
  intl: ^0.17.0
  json_annotation: ^4.1.0
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^1.3.0
  path_provider: ^2.0.5
  pkce: ^1.0.0+1
  quick_actions: ^0.6.0+7
  rxdart: ^0.27.2
  screenshot: ^1.2.3
  share_plus: ^3.0.2
  shared_preferences: ^2.0.8
  social_media_buttons:
    git:
      url: https://github.com/nrubin29/social_media_buttons
      ref: null-safety
  sqflite: ^2.0.0+4
  universal_html: ^2.0.8
  universal_io: ^2.0.4
  url_launcher: ^6.0.12
  visibility_detector: ^0.2.0
  wakelock: ^0.5.6

dev_dependencies:
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^5.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true
  adaptive_icon_background: "#ff0000"
  adaptive_icon_foreground: 'assets/images/music_note.png'
