name: finale
description: A fully-featured Last.fm client
publish_to: 'none'
version: 3.3.0+38

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  collection: ^1.17.1
  crypto: ^3.0.3
  datetime_picker_formfield: ^2.0.1
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_acrcloud: ^0.2.1
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^14.1.1
  flutter_mpmediaplayer: ^0.2.0
  flutter_web_auth: ^0.5.0
  gallery_saver: ^2.3.2
  html: ^0.15.4
  http: ^0.13.3
  in_app_review: ^2.0.6
  intl: ^0.17.0
  json_annotation: ^4.8.1
  modal_bottom_sheet: ^2.1.2
  package_info_plus: ^3.1.2
  path_provider: ^2.0.15
  pkce: ^1.1.0+1
  pool: ^1.5.1
  quick_actions: ^1.0.5
  rxdart: ^0.27.7
  screenshot: ^2.1.0
  share_plus: ^6.3.4
  shared_preferences: ^2.1.2
  sqflite: ^2.2.8+4
  uni_links: ^0.5.1
  universal_html: ^2.2.3
  universal_io: ^2.2.2
  url_launcher: ^6.1.11
  visibility_detector: ^0.4.0+2
  wakelock: ^0.6.2
  workmanager: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_launcher_icons:
    git: https://github.com/fluttercommunity/flutter_launcher_icons
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.0

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SocialMediaIcons
      fonts:
      - asset: assets/fonts/SocialMediaIcons.ttf

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true
  macos:
    generate: true
    image_path: 'assets/images/icon_rounded.png'
  web:
    generate: true
    background_color: "#f44336"
    theme_color: "#f44336"
  adaptive_icon_background: "#ff0000"
  adaptive_icon_foreground: 'assets/images/music_note.png'
