name: finale
description: A fully-featured Last.fm client
publish_to: 'none'
version: 1.6.0+24

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  charts_flutter: ^0.12.0
  collection: ^1.15.0
  crypto: ^3.0.1
  datetime_picker_formfield: ^2.0.0
  flutter:
    sdk: flutter
  flutter_acrcloud: ^0.1.5
  flutter_svg: ^1.0.0
  flutter_web_auth:
    git: https://github.com/czepiec/flutter_web_auth
  gallery_saver: ^2.3.2
  html: ^0.15.0
  http: ^0.13.4
  in_app_review: ^2.0.3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^1.3.0
  path_provider: ^2.0.7
  pkce: ^1.0.0+1
  quick_actions: ^0.6.0+8
  rxdart: ^0.27.3
  screenshot: ^1.2.3
  share_plus: ^3.0.4
  shared_preferences: ^2.0.9
  social_media_buttons:
    git:
      url: https://github.com/nrubin29/social_media_buttons
      ref: null-safety
  sqflite: ^2.0.0+4
  uni_links: ^0.5.1
  universal_html: ^2.0.8
  universal_io: ^2.0.4
  url_launcher: ^6.0.17
  visibility_detector: ^0.2.2
  wakelock: ^0.5.6

dev_dependencies:
  build_runner: ^2.1.5
  flutter_launcher_icons:
    git: https://github.com/dirkbo/flutter_launcher_icons
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_icons:
  image_path: 'assets/images/icon.png'
  image_path_macos: 'assets/images/icon_rounded.png'
  android: true
  ios: true
  macos: true
  web: true
  adaptive_icon_background: "#ff0000"
  adaptive_icon_foreground: 'assets/images/music_note.png'
