name: finale
description: A fully-featured Last.fm client
publish_to: 'none'
version: 3.1.0+33

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  charts_flutter: ^0.12.0
  collection: ^1.16.0
  crypto: ^3.0.1
  datetime_picker_formfield: ^2.0.0
  flutter:
    sdk: flutter
  flutter_acrcloud: ^0.1.6
  flutter_cache_manager: ^3.3.0
  flutter_mpmediaplayer: ^0.1.2
  flutter_web_auth: ^0.4.1
  gallery_saver: ^2.3.2
  html: ^0.15.0
  http: ^0.13.4
  in_app_review: ^2.0.4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  modal_bottom_sheet: ^2.0.1
  package_info_plus: ^1.4.2
  path_provider: ^2.0.10
  pkce: ^1.1.0+1
  pool: ^1.5.0
  quick_actions: ^0.6.0+11
  rxdart: ^0.27.3
  screenshot: ^1.2.3
  share_plus: ^4.0.4
  shared_preferences: ^2.0.15
  shared_preferences_ios: ^2.1.1
  sqflite: ^2.0.2+1
  uni_links: ^0.5.1
  universal_html: ^2.0.8
  universal_io: ^2.0.4
  url_launcher: ^6.1.2
  visibility_detector: ^0.3.3
  wakelock: ^0.6.1+2
  workmanager: ^0.5.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons:
    git: https://github.com/dirkbo/flutter_launcher_icons
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SocialMediaIcons
      fonts:
      - asset: assets/fonts/SocialMediaIcons.ttf

flutter_icons:
  image_path: 'assets/images/icon.png'
  image_path_macos: 'assets/images/icon_rounded.png'
  android: true
  ios: true
  macos: true
  web: true
  adaptive_icon_background: "#ff0000"
  adaptive_icon_foreground: 'assets/images/music_note.png'
