name: finale
description: A fully-featured Last.fm client
publish_to: 'none'
version: 3.4.2+41

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  crypto: ^3.0.3
  datetime_picker_formfield: ^2.0.1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_acrcloud: ^0.2.1
  flutter_cache_manager: ^3.3.2
  flutter_local_notifications: ^17.1.2
  flutter_mpmediaplayer: ^0.3.0
  flutter_web_auth: ^0.5.0
  gal: ^2.3.0
  html: ^0.15.4
  http: ^1.2.1
  in_app_review: ^2.0.9
  intl: ^0.19.0
  json_annotation: ^4.9.0
  modal_bottom_sheet: ^3.0.0
  octo_image: ^2.0.0
  package_info_plus: ^8.0.0
  pkce: ^1.1.0+1
  pool: ^1.5.1
  quick_actions: ^1.0.7
  rxdart: ^0.27.7
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  uni_links: ^0.5.1
  sqflite: ^2.3.3+1
  universal_html: ^2.2.4
  universal_io: ^2.2.2
  url_launcher: ^6.2.6
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.2.5
  workmanager: ^0.5.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0

dependency_overrides:
  flutter_launcher_icons:
    git: https://github.com/fluttercommunity/flutter_launcher_icons.git

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SocialMediaIcons
      fonts:
      - asset: assets/fonts/SocialMediaIcons.ttf

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true
  macos:
    generate: true
    image_path: 'assets/images/icon_rounded.png'
  web:
    generate: true
    background_color: "#f44336"
    theme_color: "#f44336"
  adaptive_icon_background: "#ff0000"
  adaptive_icon_foreground: 'assets/images/music_note.png'
