name: finale
description: A fully-featured Last.fm client
publish_to: 'none'
version: 1.3.7+18

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.0.0
  charts_flutter: ^0.11.0
  collection: ^1.15.0
  crypto: ^3.0.1
  datetime_picker_formfield: ^2.0.0
  flutter:
    sdk: flutter
  flutter_acrcloud: ^0.1.3
  flutter_svg: ^0.22.0
  flutter_web_auth:
    git: https://github.com/czepiec/flutter_web_auth
  html: ^0.15.0
  http: ^0.13.3
  in_app_review: ^2.0.2
  intl: ^0.17.0
  json_annotation: ^4.0.1
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^1.0.3
  pkce: ^1.0.0+1
  quick_actions: ^0.6.0+2
  rxdart: ^0.27.1
  screenshot: ^1.2.3
  share_plus: ^2.1.4
  shared_preferences: ^2.0.6
  social_media_buttons:
    git:
      url: https://github.com/nrubin29/social_media_buttons
      ref: null-safety
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.3
  visibility_detector: ^0.2.0
  wakelock: ^0.5.2

dev_dependencies:
  build_runner: ^2.0.5
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true
